[workspace]

resolver = "2"
members = ["mempipe", "cannoli", "jitter", "jitter_always", "cantrace"]
default-members = ["jitter_always", "cantrace"]

[env]
RUST_TEST_THREADS = "1"

[profile.dev]
opt-level = 0
debug = true
